/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_exo_snpe_battery_MainActivity_TimerHandler */

#ifndef _Included_com_example_exo_snpe_battery_MainActivity_TimerHandler
#define _Included_com_example_exo_snpe_battery_MainActivity_TimerHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
