/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_exo_snpe_battery_MainActivity */

#ifndef _Included_com_example_exo_snpe_battery_MainActivity
#define _Included_com_example_exo_snpe_battery_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_exo_snpe_battery_MainActivity
 * Method:    jniFunction
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_example_exo_1snpe_1battery_MainActivity_jniFunction
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
