/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_snpe_libvpx_MainActivity */

#ifndef _Included_com_example_snpe_libvpx_MainActivity
#define _Included_com_example_snpe_libvpx_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_snpe_libvpx_MainActivity
 * Method:    vpxDecodeVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_example_snpe_1libvpx_MainActivity_vpxDecodeVideo
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint, jint);

/*
 * Class:     com_example_snpe_libvpx_MainActivity
 * Method:    function
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_example_snpe_1libvpx_MainActivity_function
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
