/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_battery_profiler_ExoSNPE */

#ifndef _Included_com_example_battery_profiler_ExoSNPE
#define _Included_com_example_battery_profiler_ExoSNPE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_battery_profiler_ExoSNPE
 * Method:    function1
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_example_battery_1profiler_ExoSNPE_function1
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
